//! How a model's prompts are rendered and its output is read back.
//!
//! Two halves of one contract, which is why they are one trait: a template that renders
//! turns the parser cannot find is worse than no template, because it produces plausible
//! text with the reasoning and tool calls silently left inside it.
//!
//! Keyed on the ARCHITECTURE and reachable from the plan alone, like [`crate::load`]. The
//! server sniffs a chat template for the parser's markers before it builds a model, so a
//! codec that needed one would be reachable too late.

use serde_json::Value;

/// One architecture's chat format.
///
/// Implemented by a unit type per model; the bodies live in that model's
/// `chat_format` module beside the markers they use.
pub trait ChatCodec: Sync {
    /// Marker spellings this codec's PARSER needs that `template_src` never emits.
    ///
    /// A template for a different model renders fine while reasoning and tool-call
    /// extraction match nothing at all, so the server says so at load rather than
    /// letting every response come back with its reasoning inlined.
    fn markers_missing_from(&self, template_src: &str) -> Vec<&'static str>;

    /// Renders a prompt without a template: for a GGUF that carries none, or one whose
    /// template failed to compile.
    ///
    /// `bos` is the BOS token's SPELLING, from tokenizer metadata. A codec whose format
    /// starts with it uses it; one whose tokenizer prepends it instead ignores it. No
    /// codec knows a token id.
    fn render(
        &self,
        messages: &[Value],
        tools: &[Value],
        add_generation_prompt: bool,
        bos: &str,
    ) -> String;

    /// Splits generated text into (reasoning, visible).
    ///
    /// `starts_inside` says whether the generation prompt left the reasoning channel OPEN,
    /// which decides how the first generated byte is classified. Ask
    /// [`Self::prompt_ends_in_reasoning`] for it; do not assume it.
    fn split_channels(&self, text: &str, starts_inside: bool) -> (String, String);

    /// Did the rendered prompt leave the reasoning channel open?
    ///
    /// THE PROMPT IS THE ONLY HONEST SOURCE. A template branches -- Qwen3.5's emits
    /// `<think>\n` when thinking is on and `<think>\n\n</think>\n\n` when it is off, so the
    /// same model ends its prompt inside the channel in one branch and outside it in the
    /// other. `split_channels` used to hardcode "inside" for qwen35, so a request with
    /// `enable_thinking: false` filed its WHOLE answer as reasoning and returned an empty
    /// `content` -- blank in every client that renders `content`, which is all of them.
    ///
    /// Reading the prompt is also the only form that survives a template we have not seen:
    /// no request flag, no per-model table, just which marker came last.
    fn prompt_ends_in_reasoning(&self, prompt: &str) -> bool;

    /// Byte offset at which the assistant's turn ENDS inside generated text, if it does.
    ///
    /// Some formats hand the turn over mid-text rather than at a token. gemma4's model
    /// finishes a tool call by writing `<|tool_response>` -- the opener of the block a tool
    /// RESULT fills -- and the template writes the same marker when it renders that result,
    /// so the two byte streams meet exactly there. Everything past it belongs to the CALLER.
    ///
    /// Running past it is not harmless. Measured on gemma-4-E4B, two-step tool loop:
    ///
    /// ```text
    /// generated: <|tool_call>call:get_weather{city:<|"|>Oslo<|"|>}<tool_call|>
    ///            <|tool_response>response:get_weather{value:<|"|>15C, cloudy<|"|>}<tool_call|>
    ///                            ^^^^^^^^^^ the model wrote the TOOL'S answer itself
    /// ```
    ///
    /// That fabricated result came back as the assistant's visible `content`, and the next
    /// request rendered it into the prompt beside the real one. It also broke KV reuse: the
    /// real result (`4C, clear`) replaces the invented one at exactly that byte, so the
    /// re-rendered prompt stops being a prefix of what the cache holds.
    ///
    /// Return the offset OF the marker: the text before it is the turn, the marker and
    /// everything after are not the model's to write. `None` when the format's turn can only
    /// end at a token -- ChatML's `<|im_end|>` is the EOT token, which the decode loop
    /// already stops on.
    fn turn_ends_at(&self, text: &str) -> Option<usize>;

    /// Trailing bytes of the model's RAW output that cannot be classified or emitted yet.
    ///
    /// Streaming sees the answer one token at a time, and a token can land in the middle of
    /// something whose meaning is not decided until more bytes arrive:
    ///
    /// ```text
    ///   ...answer<|chan          a channel marker that may complete next token
    ///   ...answer<|tool_resp     the turn-end marker, which must not be emitted as content
    ///   ...<|channel>thou        (gemma4) a channel whose NAME decides if its body is kept
    /// ```
    ///
    /// TOOL CALLS ARE NOT THIS QUESTION. A `<tool_call>` in the model's REASONING is prose,
    /// not a call, and asking about it here holds the reasoning -- and everything after it --
    /// hostage to a close that is never coming. Ask on the visible half instead, where a call
    /// can actually occur: [`Self::unsettled_in_visible`].
    ///
    /// Everything BEFORE the returned suffix is settled forever: split it, send it, and never
    /// look at it again. That is what makes the per-token cost independent of how long the
    /// answer has grown. Cut on a char boundary -- every marker here is ASCII, so a
    /// partial-marker suffix and a `find` offset both land on one.
    fn unsettled_in_raw(&self, text: &str) -> usize;

    /// Trailing bytes of VISIBLE text the tool-call parse cannot decide yet: a call opener
    /// with no close, or a suffix that could still grow into one.
    ///
    /// The same shape as [`Self::unsettled_in_raw`], one stage later:
    ///
    /// ```text
    ///   raw ─[unsettled_in_raw]→ split_channels ─→ reasoning
    ///                                          └→ visible ─[unsettled_in_visible]→ parse_tool_calls
    /// ```
    ///
    /// Splitting first is what keeps a call marker written inside the thinking channel from
    /// stalling the whole stream: it never reaches this side.
    fn unsettled_in_visible(&self, text: &str) -> usize;

    /// The reasoning-channel state AFTER `text`, given the state before it.
    ///
    /// The streaming split classifies one settled piece at a time, so each piece has to say
    /// where it leaves the channel for the next one. Text with no marker in it changes
    /// nothing and returns `before`.
    fn channel_state_after(&self, text: &str, before: bool) -> bool;

    /// Splits the visible text into (text, calls), each call a (name, json-args) pair.
    ///
    /// Parses everything it is given. A call opener with no close is prose -- it was never
    /// going to close -- so it stays in the visible text rather than vanishing.
    ///
    /// A STREAMING CALLER CUTS FIRST, with [`Self::unsettled_in_visible`]; that is the same
    /// rule stated once instead of a flag here that restates it.
    fn parse_tool_calls(&self, text: &str) -> (String, Vec<(String, String)>);

    /// The exact text that OPENS a user turn in this format.
    ///
    /// The server needs the token where the last user message starts, to put a
    /// checkpoint there. It used to find it by re-rendering the conversation minus
    /// that message and tokenizing the result -- a second full tokenization of the
    /// whole prompt, measured at 4.5-6.0 ms on 2.8k tokens and growing linearly,
    /// paid on every request. Tokenized once at load, this turns the same question
    /// into a scan over token ids the prompt already produced.
    ///
    /// Without the trailing newline on purpose: what follows a turn opener is
    /// content, and a tokenizer is free to merge a newline with whatever comes
    /// after it, so the shortest stable spelling is the one to match.
    fn user_turn_open(&self) -> &'static str;
}

/// A REASONING CHANNEL DELIMITED BY A MARKER PAIR, shared by every format that has one.
///
/// LFM2.5 and Qwen3.5 both wrap the model's reasoning in `<think>` ... `</think>` and both
/// may open or close it in the generation prompt. Initial state, splitting and holdback
/// share one implementation; only the marker spellings belong to a model, so they are the
/// arguments. A format whose markers differ passes its own.
pub mod think {
    /// Does `prompt` end INSIDE the channel -- i.e. is the last marker in it an opener?
    ///
    /// This is what `split`'s `starts_inside` must be, and reading it off the prompt is the
    /// only form that cannot desync. Qwen3.5's template ends the prompt with `<think>\n` when
    /// thinking is on and with `<think>\n\n</think>\n\n` when it is off, so the answer is a
    /// property of the RENDERED TEXT, not of the model and not of a request flag. Hardcoding
    /// it to true cost every thinking-off request its entire visible answer.
    ///
    /// ONLY THE CURRENT ASSISTANT TURN COUNTS, so the scan starts after the last
    /// `assistant_prefix`. A `<think>` in an older turn, or one a user pasted into their own
    /// message, is not the model opening a channel it is about to generate into -- and the
    /// prompt is attacker-influenced text, so "the last marker anywhere" is the wrong rule
    /// even where it happens to give the right answer. No assistant turn means nothing is
    /// being continued, which is outside.
    ///
    /// No marker at all means outside too: a format that never opened the channel never
    /// entered it.
    #[must_use]
    pub fn ends_inside(prompt: &str, assistant_prefix: &str, open: &str, close: &str) -> bool {
        let turn = prompt
            .rsplit_once(assistant_prefix)
            .map_or("", |(_, turn)| turn);
        state_after(turn, open, close, false)
    }

    /// The state after `text`, given the state `before` it: the LAST marker decides, and
    /// text carrying no marker leaves the state alone.
    ///
    /// [`ends_inside`] is this with `before = false`, because a prompt that has never
    /// opened the channel has never entered it. The streaming split needs the general form:
    /// it classifies one settled piece at a time, and a piece may contain no marker at all.
    #[must_use]
    pub fn state_after(text: &str, open: &str, close: &str, before: bool) -> bool {
        match (text.rfind(open), text.rfind(close)) {
            (Some(o), Some(c)) => o > c,
            (Some(_), None) => true,
            (None, Some(_)) => false,
            (None, None) => before,
        }
    }

    /// Trailing bytes that could still grow into `open` or `close`, or that sit inside a
    /// `open`..`close` pair that has not closed yet. See `ChatCodec::unsettled_in_visible`.
    #[must_use]
    pub fn unsettled_pair(text: &str, open: &str, close: &str) -> usize {
        // An OPEN with no close is unsettled from the opener on: whether the bytes after it
        // are a tool call or ordinary prose is not known until the close arrives.
        let mut rest = text;
        let mut at = 0usize;
        while let Some(i) = rest.find(open) {
            let after = &rest[i + open.len()..];
            let Some(end) = after.find(close) else {
                return text.len() - (at + i);
            };
            at += i + open.len() + end + close.len();
            rest = &after[end + close.len()..];
        }
        // No opener is pending, so the only undecided bytes are a partial marker at the very
        // end -- which is a property of what is LEFT, not of the whole text.
        holdback(rest, open, close)
    }

    /// Splits `text` into `(reasoning, visible)` on a marker pair.
    ///
    /// `starts_inside` must be true when the generation prompt ended in the opening
    /// marker, because the generated deltas then begin inside the channel and usually
    /// contain only the closing one.
    #[must_use]
    pub fn split(text: &str, open: &str, close: &str, starts_inside: bool) -> (String, String) {
        let mut reasoning = String::new();
        let mut visible = String::new();
        let mut rest = text;
        let mut inside = starts_inside;

        while !rest.is_empty() {
            if inside {
                match earliest(rest.find(open), rest.find(close)) {
                    Some((at, Marker::Open)) => {
                        reasoning.push_str(&rest[..at]);
                        rest = &rest[at + open.len()..];
                    }
                    Some((at, Marker::Close)) => {
                        reasoning.push_str(&rest[..at]);
                        rest = &rest[at + close.len()..];
                        inside = false;
                    }
                    None => {
                        reasoning.push_str(rest);
                        break;
                    }
                }
            } else if let Some(at) = rest.find(open) {
                visible.push_str(&rest[..at]);
                rest = &rest[at + open.len()..];
                inside = true;
            } else {
                visible.push_str(rest);
                break;
            }
        }
        (reasoning, visible)
    }

    #[derive(Clone, Copy)]
    enum Marker {
        Open,
        Close,
    }

    fn earliest(open: Option<usize>, close: Option<usize>) -> Option<(usize, Marker)> {
        match (open, close) {
            (Some(open), Some(close)) if open <= close => Some((open, Marker::Open)),
            (Some(_) | None, Some(close)) => Some((close, Marker::Close)),
            (Some(open), None) => Some((open, Marker::Open)),
            (None, None) => None,
        }
    }

    /// Length of the longest strict suffix of `text` that can still grow into `marker`
    /// on the next streaming delta.
    #[must_use]
    pub fn partial_marker_len(text: &str, marker: &str) -> usize {
        let max = marker.len().saturating_sub(1).min(text.len());
        (1..=max)
            .rev()
            .find(|&length| text.ends_with(&marker[..length]))
            .unwrap_or(0)
    }

    /// Holdback for either boundary of the pair: whichever suffix could still complete.
    #[must_use]
    pub fn holdback(text: &str, open: &str, close: &str) -> usize {
        partial_marker_len(text, open).max(partial_marker_len(text, close))
    }
}

/// The chat codec for a plan's architecture.
///
/// The one place an architecture name maps to a codec, and the companion to
/// [`crate::load`]: that turns a description into something that runs, this turns it into
/// something that can be talked to.
///
/// # Errors
/// When the architecture has no codec.
pub fn codec(plan: &crate::ModelPlan) -> Result<&'static dyn ChatCodec, String> {
    match plan.config.architecture.as_str() {
        "gemma4" => Ok(&crate::gemma4::chat_format::Codec),
        "lfm2" => Ok(&crate::lfm2::chat_format::Codec),
        "qwen35" => Ok(&crate::qwen35::chat_format::Codec),
        other => Err(format!("no chat codec for architecture '{other}'")),
    }
}
