#!/usr/bin/env python3
"""Build the paper's conversation test set from PUBLIC sources. Nothing in it is written by us.

The paper's harness (../harness/agentic.py) fixes the measurement protocol: multi-turn,
context that grows across turns, replies that run to their end, one learned store per arm.
The prompts are the part that could be tilted toward our own method, so every turn comes
from a published dataset, picked by a fixed rule, and the built files are committed with the
source revision and a hash per conversation.

THE RULES
  1. No turn is invented. A single-turn source gives a single-turn conversation; nothing is
     padded, paraphrased or followed up by us.
  2. Selection is the dataset's own order: the first items that pass the stated filters.
     No seed, no sampling, no look at how any engine does on an item.
  3. Balance on ROUNDS per kind, not conversations, so every per-kind cell rests on the same
     number of timed rounds (an MT-Bench item is two turns, a translation item one).
  4. One length cap per source (`--max-chars`), because every arm must finish. A LongBench
     context over the cap is cut from the MIDDLE, LongBench's own rule (the head and the tail
     are what the task's question refers to); such a conversation carries "truncated".
  5. The only edits to source text are format conversions, each named where it is made:
     ConvFinQA's flattened turns reduced to their own question, ToolACE's Python-style
     parameter types ("dict", "float", "int", ...) renamed to the JSON Schema types they name.

SOURCES (licence as the source states it)
  specbench   hemingkx/Spec-Bench question.jsonl (Apache-2.0), the standard speculative-
              decoding benchmark: MT-Bench's two-turn items plus translation, summarization,
              QA, math reasoning and RAG.
  speedbench  nvidia/SPEED-Bench `qualitative` (NVIDIA licence, "other"): 11 categories.
  wildchat    allenai/WildChat (ODC-BY): real user conversations; USER turns only, the
              assistant turns are generated by the model under test.
  convfinqa   ChanceFocus/flare-convfinqa: multi-turn questions over a real earnings report.
  toolace     Team-ACE/ToolACE (Apache-2.0): multi-turn tool use with the source's own
              schemas and its own structured tool results fed back.
  longbench   THUDM/LongBench (MIT) data.zip with the benchmark's own task prompt.

REPRODUCING. GitHub sources are fetched at a pinned commit. The Hugging Face datasets
server serves a dataset's current revision, so the revision in force is recorded in each
file's `provenance`, and every conversation carries its source row id and a sha256 of its
text: a rebuild that differs says which conversation moved.

usage: build.py [OUT_DIR] [--rounds-per-kind 2] [--single-kind 8] [--max-chars 4000]
                [--longbench-data DIR]
"""
import hashlib
import io
import json
import os
import sys
import time
import urllib.error
import urllib.request
import zipfile

HERE = os.path.dirname(os.path.abspath(__file__))

SPEC_BENCH_REV = "fd2c1cd7d2201ef71db4c5f4e455008f017967bf"
SPEC_BENCH_URL = (f"https://raw.githubusercontent.com/hemingkx/Spec-Bench/{SPEC_BENCH_REV}/"
                  "data/spec_bench/question.jsonl")
LONGBENCH_REV = "2e00731f8d0bff23dc4325161044d0ed8af94c1e"
LONGBENCH_PROMPTS = (f"https://raw.githubusercontent.com/THUDM/LongBench/{LONGBENCH_REV}/"
                     "LongBench/config/dataset2prompt.json")
LONGBENCH_DATA_REV = "5e628be450b7e67fb7ae6e201bd6d8f7056f7672"
LONGBENCH_DATA = (f"https://huggingface.co/datasets/zai-org/LongBench/resolve/"
                  f"{LONGBENCH_DATA_REV}/data.zip")
LONGBENCH_TASKS = ("gov_report", "qasper", "lcc", "repobench-p", "vcsum", "multi_news")
ROWS = ("https://datasets-server.huggingface.co/rows?dataset={ds}&config={cfg}"
        "&split={split}&offset={off}&length={n}")
# The source protocol's generation cap (Spec-Bench: 1024 new tokens), recorded so a run that
# uses another cap says so. The paper's runs let replies finish: a thinking model's reply is
# cut inside its reasoning at 1024.
SOURCE_MAX_TOKENS = 1024


def get(url, tries=4, binary=False):
    """GET with retries: the datasets server answers 502 often enough to matter, and a
    half-built set that looks complete is worse than a loud failure."""
    for attempt in range(tries):
        try:
            with urllib.request.urlopen(url, timeout=300) as r:
                body = r.read()
                return body if binary else body.decode("utf-8")
        except (urllib.error.HTTPError, urllib.error.URLError, TimeoutError) as e:
            if attempt == tries - 1:
                raise
            print(f"    retry {attempt + 1}/{tries - 1} after {e}", file=sys.stderr)
            time.sleep(2 * (attempt + 1))
    raise AssertionError("unreachable")


def hf_revision(ds):
    """The revision the datasets server is serving now; recorded, not chosen."""
    info = json.loads(get(f"https://huggingface.co/api/datasets/{ds}"))
    return info.get("sha")


def rows(ds, config, split, offset, n=100):
    url = ROWS.format(ds=ds.replace("/", "%2F"), cfg=config, split=split, off=offset, n=n)
    return [x["row"] for x in json.loads(get(url)).get("rows", [])]


def conversation(name, kind, turns, source, src_id):
    """One conversation in the harness's format, with its provenance beside it. A turn's
    `type` is its position only ("first" / "continued"): we do not know where an imported
    conversation changes topic, and a label we cannot justify is worse than none."""
    joined = "\n".join(turns)
    return {
        "name": name,
        "kind": kind,
        "source": source,
        "source_id": str(src_id),
        "chars": len(joined),
        "sha256": hashlib.sha256(joined.encode("utf-8")).hexdigest()[:16],
        "turns": [
            {"kind": kind, "type": "first" if i == 0 else "continued", "text": t}
            for i, t in enumerate(turns)
        ],
    }


def enough(convs, kind, target):
    """Has `kind` reached `target` rounds (rule 3)?"""
    return sum(len(c["turns"]) for c in convs if c["kind"] == kind) >= target


def build_specbench(rounds_per_kind, max_chars):
    rows_ = [json.loads(l) for l in get(SPEC_BENCH_URL).splitlines() if l.strip()]
    by_cat = {}
    for r in rows_:
        by_cat.setdefault(r["category"], []).append(r)
    out, skipped = [], 0
    for cat in sorted(by_cat):
        taken = 0
        for r in by_cat[cat]:
            if enough(out, cat, rounds_per_kind):
                break
            turns = [str(t) for t in r["turns"]]
            if sum(len(t) for t in turns) > max_chars:
                skipped += 1
                continue
            taken += 1
            out.append(conversation(f"sb-{cat}-{taken}", cat, turns, "hemingkx/Spec-Bench",
                                    r["question_id"]))
    print(f"    spec-bench: {skipped} instances skipped over {max_chars} chars")
    return out, {"source": "hemingkx/Spec-Bench", "revision": SPEC_BENCH_REV,
                 "url": SPEC_BENCH_URL, "skipped_over_cap": skipped}


def build_speedbench(rounds_per_kind, max_chars):
    rev = hf_revision("nvidia/SPEED-Bench")
    out, seen, skipped = [], {}, 0
    for offset in range(0, 880, 100):
        for r in rows("nvidia/SPEED-Bench", "qualitative", "test", offset):
            cat = r["category"]
            if enough(out, cat, rounds_per_kind):
                continue
            turns = [str(t) for t in r["turns"]]
            if sum(len(t) for t in turns) > max_chars:
                skipped += 1
                continue
            seen[cat] = seen.get(cat, 0) + 1
            out.append(conversation(f"sp-{cat}-{seen[cat]}", cat, turns,
                                    "nvidia/SPEED-Bench:qualitative", r["question_id"]))
    return out, {"source": "nvidia/SPEED-Bench", "config": "qualitative", "split": "test",
                 "revision": rev, "skipped_over_cap": skipped}


def build_wildchat(n_conversations, max_chars, min_turns=4):
    """USER turns only, filtered on the dataset's own columns (English, not toxic, not
    redacted, at least `min_turns` user turns); a longer conversation is TRUNCATED to its
    first four user turns."""
    rev = hf_revision("allenai/WildChat")
    out, scanned = [], 0
    for offset in range(0, 20000, 100):
        if len(out) == n_conversations:
            break
        for r in rows("allenai/WildChat", "default", "train", offset):
            scanned += 1
            if len(out) == n_conversations:
                break
            if r.get("turn", 0) < min_turns or r.get("language") != "English":
                continue
            if r.get("toxic") or r.get("redacted"):
                continue
            users = [m["content"] for m in r["conversation"] if m["role"] == "user"]
            users = [u for u in users if u and u.strip()][:4]
            if len(users) < min_turns or sum(len(u) for u in users) > max_chars:
                continue
            out.append(conversation(f"wc-{len(out) + 1}", "wildchat", users,
                                    "allenai/WildChat", r["conversation_id"]))
    print(f"    wildchat: {len(out)} kept from {scanned} scanned")
    return out, {"source": "allenai/WildChat", "config": "default", "split": "train",
                 "revision": rev, "scanned": scanned}


def build_convfinqa(n_dialogues, max_chars):
    """The `flare-convfinqa` rows are FLATTENED -- each turn's query repeats the document and
    the history -- because that set is scored one prompt at a time. The harness carries the
    history itself, so turn 0 is taken whole and each later turn is reduced to its own
    question: the text after the last `Question:` marker (rule 5). A dialogue whose turns do
    not carry that marker is dropped, not guessed at."""
    rev = hf_revision("ChanceFocus/flare-convfinqa")
    by_dlg, dropped = {}, 0
    for offset in range(0, 600, 100):
        for r in rows("ChanceFocus/flare-convfinqa", "default", "test", offset):
            by_dlg.setdefault(str(r["dialogue_id"]), []).append(r)
        if len(by_dlg) > n_dialogues * 3:
            break
    out = []
    for dlg in sorted(by_dlg, key=lambda d: int(d) if d.isdigit() else 0):
        if len(out) == n_dialogues:
            break
        turns_in = sorted(by_dlg[dlg], key=lambda r: int(r["turn"]))
        if len(turns_in) < 2 or len(turns_in[0]["query"]) > max_chars:
            continue
        texts, ok = [turns_in[0]["query"]], True
        for r in turns_in[1:]:
            q = r["query"]
            if "Question:" not in q:
                ok = False
                break
            follow = q.rsplit("Question:", 1)[1].rsplit("Answer:", 1)[0].strip()
            if not follow:
                ok = False
                break
            texts.append(follow)
        if not ok:
            dropped += 1
            continue
        out.append(conversation(f"cf-{len(out) + 1}", "finance", texts,
                                "ChanceFocus/flare-convfinqa", dlg))
    print(f"    convfinqa: {dropped} dialogues dropped for an unparsable follow-up")
    return out, {"source": "ChanceFocus/flare-convfinqa", "config": "default",
                 "split": "test", "revision": rev, "dropped_unparsable": dropped}


# ToolACE's parameter types are Python's names; the wire format is JSON Schema, which has no
# "dict", "float" or "int". An engine that validates the schema refuses the request (llama.cpp
# builds a tool-call parser for Qwen3's template and stops at "unrecognized type float"), so each
# is renamed to the JSON Schema type it names (rule 5). Nothing else in a schema is touched.
JSON_SCHEMA_TYPE = {"dict": "object", "float": "number", "int": "integer", "str": "string",
                    "bool": "boolean", "list": "array", "tuple": "array"}


def json_schema_types(x):
    """`x` with every Python-style `type` renamed, through nested properties and items."""
    if isinstance(x, dict):
        out = {k: json_schema_types(v) for k, v in x.items()}
        if isinstance(out.get("type"), str):
            out["type"] = JSON_SCHEMA_TYPE.get(out["type"], out["type"])
        return out
    if isinstance(x, list):
        return [json_schema_types(v) for v in x]
    return x


def toolace_schemas(system_text):
    """The function list ToolACE puts in its system prompt, as OpenAI tool schemas, with
    Python-style parameter types renamed to JSON Schema's; that rename is the whole conversion
    (rule 5)."""
    head = "you can invoke:\n"
    if head not in system_text:
        return None
    body = system_text.split(head, 1)[1]
    body = body.rsplit("].", 1)[0] + "]" if "]." in body else body
    try:
        funcs = json.loads(body)
    except json.JSONDecodeError:
        return None
    out = []
    for f in funcs:
        params = json_schema_types(f.get("parameters") or {"type": "object", "properties": {}})
        out.append({"type": "function", "function": {
            "name": f.get("name", ""), "description": f.get("description", ""),
            "parameters": params}})
    return out or None


def build_toolace(n_conversations, max_chars):
    """A row is `user -> assistant(call) -> tool(result) -> assistant -> user ...`. Each USER
    message becomes a turn; where the assistant answered with a call and a `tool` message came
    back, that message's text becomes the turn's `result`, fed back when the model under test
    calls a tool on that turn."""
    rev = hf_revision("Team-ACE/ToolACE")
    out, no_schema = [], 0
    for offset in range(0, 3000, 50):
        if len(out) == n_conversations:
            break
        for r in rows("Team-ACE/ToolACE", "default", "train", offset, 50):
            if len(out) == n_conversations:
                break
            tools = toolace_schemas(r.get("system", ""))
            if not tools:
                no_schema += 1
                continue
            conv = r["conversations"]
            if isinstance(conv, str):
                conv = json.loads(conv)
            turns, results, i = [], [], 0
            while i < len(conv):
                if conv[i]["from"] != "user":
                    i += 1
                    continue
                turns.append(str(conv[i]["value"]))
                result = None
                if i + 2 < len(conv) and conv[i + 1]["from"] == "assistant" \
                        and conv[i + 2]["from"] == "tool":
                    result = str(conv[i + 2]["value"])
                results.append(result)
                i += 1
            turns, results = turns[:4], results[:4]
            if len(turns) < 2 or not any(results):
                continue
            size = sum(len(t) for t in turns) + sum(len(x) for x in results if x)
            if size > max_chars:
                continue
            c = conversation(f"ta-{len(out) + 1}", "tools", turns, "Team-ACE/ToolACE",
                             offset + len(out))
            c["tools"] = tools
            for t, res in zip(c["turns"], results):
                if res:
                    t["result"] = res
            out.append(c)
    print(f"    toolace: {no_schema} rows had no parsable schema list")
    return out, {"source": "Team-ACE/ToolACE", "config": "default", "split": "train",
                 "revision": rev, "no_schema": no_schema}


def longbench_data(data_dir):
    """LongBench's data.zip at a pinned revision, unpacked once into `data_dir`."""
    if all(os.path.exists(os.path.join(data_dir, f"{t}.jsonl")) for t in LONGBENCH_TASKS):
        return data_dir
    print(f"    longbench: fetching data.zip at {LONGBENCH_DATA_REV[:12]}")
    z = zipfile.ZipFile(io.BytesIO(get(LONGBENCH_DATA, binary=True)))
    os.makedirs(data_dir, exist_ok=True)
    for t in LONGBENCH_TASKS:
        with open(os.path.join(data_dir, f"{t}.jsonl"), "wb") as f:
            f.write(z.read(f"data/{t}.jsonl"))
    return data_dir


def build_longbench(data_dir, rounds_per_kind, max_chars):
    """LongBench's own instruction around each document (the task template from the
    benchmark's config), one turn per conversation because LongBench is single-turn."""
    prompts = json.loads(get(LONGBENCH_PROMPTS))
    out, cut_n = [], 0
    for task in LONGBENCH_TASKS:
        template, taken = prompts.get(task), 0
        with open(os.path.join(data_dir, f"{task}.jsonl"), encoding="utf-8") as f:
            for line in f:
                if enough(out, task, rounds_per_kind):
                    break
                r = json.loads(line)
                ctx, cut = r["context"], False
                text = template.format(context=ctx, input=r.get("input", ""))
                if len(text) > max_chars:
                    room = max(0, len(ctx) - (len(text) - max_chars))
                    if room < 2000:
                        continue
                    ctx = ctx[: room // 2] + ctx[len(ctx) - (room - room // 2):]
                    text = template.format(context=ctx, input=r.get("input", ""))
                    cut = True
                taken += 1
                c = conversation(f"lb-{task}-{taken}", task, [text], "THUDM/LongBench",
                                 r.get("_id", taken))
                if cut:
                    c["truncated"] = "middle"
                    cut_n += 1
                out.append(c)
    return out, {"source": "THUDM/LongBench", "revision": LONGBENCH_DATA_REV,
                 "prompts_revision": LONGBENCH_REV, "tasks": list(LONGBENCH_TASKS),
                 "truncated_middle": cut_n}


def balance_report(convs):
    per = {}
    for c in convs:
        per[c["kind"]] = per.get(c["kind"], 0) + len(c["turns"])
    lo, hi = min(per.values()), max(per.values())
    flag = "" if hi <= lo + 1 else f"   UNBALANCED {lo}..{hi}"
    return ", ".join(f"{k} {v}" for k, v in sorted(per.items())) + flag


def write(out_dir, name, built, params):
    convs, prov = built
    if not convs:
        sys.exit(f"{name}: no conversation passed the filters -- refusing to write an empty set")
    prov = {**prov, "builder": "dspark-paper/testset/build.py", "params": params,
            "built": time.strftime("%Y-%m-%dT%H:%M:%S%z")}
    path = os.path.join(out_dir, f"{name}.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump({"set": name, "source_max_tokens": SOURCE_MAX_TOKENS, "provenance": prov,
                   "conversations": convs}, f, ensure_ascii=False, indent=1)
    rounds = sum(len(c["turns"]) for c in convs)
    print(f"{name:<11} {len(convs):>4} conversations {rounds:>4} rounds "
          f"{sum(c['chars'] for c in convs) / 1000:>7.1f}k chars  -> {path}")
    print("            rounds per kind: " + balance_report(convs))


def arg(flag, default):
    return type(default)(sys.argv[sys.argv.index(flag) + 1]) if flag in sys.argv else default


if __name__ == "__main__":
    pos = [a for i, a in enumerate(sys.argv[1:], 1)
           if not a.startswith("--") and not sys.argv[i - 1].startswith("--")]
    out_dir = pos[0] if pos else os.path.join(HERE, "sets")
    per_kind = arg("--rounds-per-kind", 2)
    n_single = arg("--single-kind", 8)
    max_chars = arg("--max-chars", 4000)
    lb_dir = arg("--longbench-data", os.path.join(HERE, ".cache", "longbench"))
    params = {"rounds_per_kind": per_kind, "single_kind": n_single, "max_chars": max_chars}
    os.makedirs(out_dir, exist_ok=True)
    write(out_dir, "specbench", build_specbench(per_kind, max_chars), params)
    write(out_dir, "speedbench", build_speedbench(per_kind, max_chars), params)
    write(out_dir, "wildchat", build_wildchat(n_single, max_chars), params)
    write(out_dir, "convfinqa", build_convfinqa(n_single, 3 * max_chars), params)
    write(out_dir, "toolace", build_toolace(n_single, 3 * max_chars), params)
    write(out_dir, "longbench",
          build_longbench(longbench_data(lb_dir), per_kind, 3 * max_chars), params)
